### ISSUE TITLE
Small screen

### ISSUE THREAD

**Issue by jamesryanbell** [longsleep/sunxi-disp-tool#2]
Hi

I have followed all the steps but when I change to 4k mode (2160p30) all I get is a small screen in the top left. Any ideas?

Thanks,
James

**Comment by longsleep** [comment]
If a resolution actually works as expected does depend solely on the Kernel and its display drivers. `sunxi-disp-tool` meerly tells it what to do. What board do you try with 2160p30 ?

**Comment by jamesryanbell** [comment]
I have a pine64 2GB model - https://shop.pine64.com/collections/board/products/pine-a64-board-2gb

I have installed - Ubuntu Linux Image [20160501] based on Longsleep build, updated by Pine64 and followed the tutorial in this post: http://forum.pine64.org/showthread.php?tid=980

Thanks,
James
